// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxAxpAuwukJztyvR24DcGwRT_CB_UbXEA',
    appId: '1:978964631771:web:af176fad585393b2be3cfe',
    messagingSenderId: '978964631771',
    projectId: 'authtest-f3459',
    authDomain: 'authtest-f3459.firebaseapp.com',
    storageBucket: 'authtest-f3459.appspot.com',
    measurementId: 'G-ZY4T5JRB61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx8coLOa27BrfoHP64_MYBej5ePuUNqnc',
    appId: '1:978964631771:android:ba7fda71bb2b55c1be3cfe',
    messagingSenderId: '978964631771',
    projectId: 'authtest-f3459',
    storageBucket: 'authtest-f3459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0gJhT_utPMvf3rryk7Gt1bAdbS7_KZRs',
    appId: '1:978964631771:ios:fa02ca4c4fe7c145be3cfe',
    messagingSenderId: '978964631771',
    projectId: 'authtest-f3459',
    storageBucket: 'authtest-f3459.appspot.com',
    iosClientId: '978964631771-g1llnuvaf2vpi637so81tg0jm3d6oocr.apps.googleusercontent.com',
    iosBundleId: 'com.example.authMyExemple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0gJhT_utPMvf3rryk7Gt1bAdbS7_KZRs',
    appId: '1:978964631771:ios:fa02ca4c4fe7c145be3cfe',
    messagingSenderId: '978964631771',
    projectId: 'authtest-f3459',
    storageBucket: 'authtest-f3459.appspot.com',
    iosClientId: '978964631771-g1llnuvaf2vpi637so81tg0jm3d6oocr.apps.googleusercontent.com',
    iosBundleId: 'com.example.authMyExemple',
  );
}
